### ISSUE TITLE
 Let the test suite run on non-intel architectures

### ISSUE THREAD

**Issue by Bischoff** [SUSE/spacewalk-testsuite-base#252]
Currently the test suite runs surprisingely well on non-intel architectures ;-) .

However the problems are many. One of them is that fake packages like ```orion-dummy``` exist only for i586 and ppc64le in ```TestRepo```  directory. Of course that's only one of the examples.

**Comment by MalloZup** [comment]
this will never happen @Bischoff . ( just in realisti timeline/perspective). 

I think is better to have issue that are realistic.
I would really like to have this , we will never achieve this, due to lack of people, maintenance for that.

Feel free to reopen, but this is something we cannot do it in short/longterm even
